### ISSUE TITLE
AES 

### ISSUE THREAD

**Issue by AlfaOmega33** [js-labs/WalkieTalkie#10]
It would be possible to add AES technologies to encrypt communications?

**Comment by js-labs** [comment]
Hi!
Why it can be useful for local communication?

**Comment by AlphaOmega3** [comment]
to prevent third "listen" the conversation: ideally, a secure communication between 2 cell would using a third cell as router, in order to create a network private, However, Samsung not allows you to use the router without SIM card .. then the router must to connect to Internet .. is a strange thing. in addition, considering that the bulk of turnover of companies telecommunications derived from the sale of our data to government and private .. and, finally, the WiFi is not inviolable and, potenzially, you can obtain data, pictures, password, etc. --- in short, maintain privacy in the things that we do is one of our law, and I think encryption is a first step to protect us (excuse the text huge, but since you have responded I didn't want to be rude. currency the situation and you decide. greetings.

**Comment by buckshee** [comment]
This software is very much like a PMR over 802.11, so you can use WPA to get AES (IMO)

**Comment by js-labs** [comment]
The app was actually conceived as a toy. Adding features like encryption will turn it to the professional tool, so I will have to take money for it :)

**Comment by AlphaOmega3** [comment]
And how much money are we talking about?

**Comment by js-labs** [comment]
Hi, sorry for the late reply.
Regarding the money: I have no idea yet... Do you think there are many people ready to pay for such feature?

**Comment by AlphaOmega3** [comment]
I'm sorry but I have no idea. perhaps, for the moment, add a bitcoin address within the app, and if you give a lot, implements encryption.
